### ISSUE TITLE
DumpExtensions not found/available?

### ISSUE THREAD

**Issue by leroypijlman** [Kir-Antipov/VisualDump#4]
I successfully installed the extension, and have the VisualDump window opened. 
But I am unable to call DumpExtensions.EnableDumping(), because DumpExtensions can not be found. Anything I am missing?

Love the idea of this extension so much. Just wish it was available without calling the extension method.

**Comment by Kira-NT** [comment]
Hi!
VisualDump works on the principle of associating your program with a receiving server, where we can send dumps' data (in our case such a server is Visual Studio). 
Therefore, the work requires a library-interlayer, which will assume responsibilities in the search and communication with the server. 
This library is [DumpExtensions](https://www.nuget.org/packages/DumpExtensions/). Usually it's added to the project automatically, but something can go wrong in the `IVsPackageInstaller` interface, so you have to manually add it... Sorry about that


> Just wish it was available without calling the extension method

Do you mean to exclude the `DumpExtensions.EnableDumping()` call? If so, then I have some good news for you about `VisualDump 2.0` :wink:

**Comment by leroypijlman** [comment]
Aha! Adding the package manually worked, didn't know it had to be added. 
Problem solved. :)

> Do you mean to exclude the DumpExtensions.EnableDumping() call? If so, then I have some good news for you about VisualDump 2.0 😉

I'm REALLY excited for this. Looked for this for way too long and almost considered writing the extension myself. Great work!

**Comment by Kira-NT** [comment]
Finally, I completed this update and already published it to the Marketplace!

Glad you're using Visual Dump! :D

**Comment by leroypijlman** [comment]
Holy cow, that was fast!

I can not wait till monday to try it out at work and introduce it to all my colleagues. 💯 👍

**Comment by Kira-NT** [comment]
I just started working on this update exactly one day before your issue :smile_cat: 

I really hope that you and your colleagues will like this update) 
If you'll have any ideas or suggestions - issues are always open for you!)
